import {command as c} from '../../content/command';
const e=(s:string)=>s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]!));
const button=(label:string,href:string,primary=false)=>`<a class="button ${primary?'primary':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const meta=(s:string)=>`<p class="meta">${s}</p>`;
export function clip(kind:string,index=0){
 const data=c.walkthrough[index];
 const contents:Record<string,string>={
 prepare:`<div class="message" data-beat="0">${e(data.prompt)}</div><div class="thinking" data-beat="1"><span class="working"></span>Drafting effect</div><div class="effect" data-beat="2">${meta('PROPOSED EFFECT / 001')}<h4>Evidence capsule</h4><dl><div><dt>Principal</dt><dd>VERA-04</dd></div><div><dt>Computer</dt><dd>CC-004</dd></div><div><dt>Scope</dt><dd>capsule.prepare</dd></div></dl><p class="quiet">Prepared for authority review</p></div>`,
 authority:`<p class="prompt" data-beat="0">Which authority envelope should govern this effect?</p><div class="envelopes" data-beat="1"><div class="selected"><span>01</span>Regency Core<i>Selected</i></div><div><span>02</span>Continuum Computer</div><div><span>03</span>OPS</div></div><p data-beat="2" class="quiet">Scope attached · Awaiting operator review</p>`,
 release:`<p class="quiet" data-beat="0">Effect Boundary / demonstration</p><div class="effect" data-beat="1">${meta('EFFECT / 001')}<h4>Effect released <span class="tick" aria-label="demonstration recorded">✓</span></h4><dl><div><dt>Principal</dt><dd>VERA-04</dd></div><div><dt>Revision</dt><dd>REV-003</dd></div><div><dt>Record</dt><dd>REC-004</dd></div></dl><a href="#trust" class="text-link">View evidence <span>↗</span></a></div><p class="quiet" data-beat="2">Illustrative receipt · No external effect</p>`,
 trace:`<div class="record-row" data-beat="0"><span>REC-001</span><strong>Proposal prepared</strong></div><div class="record-row" data-beat="1"><span>REC-002</span><strong>Authority reviewed</strong></div><div class="record-row" data-beat="2"><span>REC-003</span><strong>Effect mediated</strong></div><div class="record-row" data-beat="3"><span>REC-004</span><strong>Ledger record</strong></div><div class="requirement" data-beat="4">Evidence required <span class="tick">✓</span></div>`,
 confirm:`<div class="effect" data-beat="0">${meta('REVIEW EFFECT / REV-003')}<h4>Prepare evidence capsule</h4><dl><div><dt>Principal</dt><dd>VERA-04</dd></div><div><dt>Authority</dt><dd>Regency Core</dd></div><div><dt>Scope</dt><dd>capsule.prepare</dd></div></dl><label class="edit-label" hidden>Capsule label<input id="capsule-name" value="Evidence capsule" maxlength="60"></label></div><p class="confirmation-state" role="status" data-beat="1">Review the exact proposal before release.</p><div class="confirm-actions" data-beat="2"><button type="button" data-action="edit">Make edits</button><button type="button" data-action="cancel">Cancel</button><button type="button" data-action="release" class="small-primary">Release effect</button></div>`,
 };
 return `<div class="demo-clip" data-clip="${kind}" data-state="poster"><div class="demo-top"><span class="mini-mark" aria-hidden="true">/::/</span><div><strong>Command</strong><span>Continuum operator</span></div><span class="demo-label">Demonstration</span></div><div class="demo-body">${contents[kind]}</div><div class="demo-bottom"><span>VERA-04 / CC-004</span><button class="clip-toggle" type="button" aria-label="Pause ${kind} demonstration">Pause</button></div></div>`;
}
export function render(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0A0A0A"><meta name="description" content="Explore a conceptual Command interface for Asentxia Continuum: prepared work, scoped authority, and ordered evidence."><title>Command — Continuum / Asentxia Systems</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/command/command.css"><script>if(!matchMedia("(prefers-reduced-motion: reduce)").matches){document.documentElement.classList.add("motion-pending");setTimeout(()=>document.documentElement.classList.remove("motion-pending"),3500)}</script><script type="module" src="/command/assets/command.js"></script></head><body><a class="skip" href="#walkthrough">Skip animation</a><div id="particle-root" aria-hidden="true"></div><header class="header"><a class="brand" href="/">ASENTXIA <span>SYSTEMS</span></a><nav aria-label="Command navigation"><a href="/continuum/">Continuum</a><a href="/architecture/">Architecture</a><a href="/#evidence">Inspect evidence <span aria-hidden="true">↗</span></a></nav><button id="motion-toggle" type="button" aria-pressed="false">Pause motion</button></header><main>
<section id="opening" class="opening"><div class="opening-stage"><div class="hero"><p class="eyebrow load-item">${c.eyebrow}</p><h1 class="load-item">Command the<br><em>continuum.</em></h1><p class="hero-sub load-item">${c.description}</p><div class="actions load-item">${button('Enter Continuum','/continuum/',true)}${button('Trace the architecture','/architecture/')}</div><p class="hero-note load-item">Conceptual product experience <span> / </span> Explore the demonstration below</p></div><div class="ring-labels" aria-hidden="true">${c.labels.map((label,i)=>`<p data-label="${i}"><span>0${i+1} / </span>${label}</p>`).join('')}</div><div class="scene-foot"><span>CONTINUUM / COMMAND</span><span>SCROLL TO EXPLORE ↓</span><span>PRINCIPAL / VERA</span></div><div class="title-wipe"><h2>${c.lock}</h2></div></div></section>
<section id="walkthrough" class="walkthrough" aria-label="Command walkthrough"><div class="walk-stage"><div class="section-heading">${meta('THE OPERATOR / DEMONSTRATION')}<p>${c.demoNote}</p></div><div class="walk-panels">${c.walkthrough.map((item,i)=>`<article class="walk-panel" data-panel="${i}">${clip(item.kind,i)}<div class="walk-copy">${meta(`0${i+1} / 03`)}<h2>${item.title}</h2><p>${item.body}</p></div></article>`).join('')}</div><div class="walk-controls"><span id="walk-count">01 / 03</span><div>${c.walkthrough.map((x,i)=>`<button type="button" data-step="${i}" aria-label="Show demonstration ${i+1}" aria-pressed="${i===0}"><span></span></button>`).join('')}</div><a href="#capabilities">Explore the workflows ↓</a></div></div></section>
<section id="capabilities" class="capabilities section-pad"><div class="section-intro">${meta('INTENT / PREPARED WORK')}<h2>Say what you need.<br><em>See how it would work.</em></h2><p>Five conceptual workflows inside one persistent environment.</p></div><div class="capability-layout"><div class="accordion">${c.accordion.map((x,i)=>`<div class="accordion-row"><h3><button id="acc-${i}" aria-expanded="${i===0}" aria-controls="acc-body-${i}" data-accordion="${i}"><span class="row-number">0${i+1}</span>${x.title}<span class="row-icon" aria-hidden="true">${i===0?'−':'+'}</span></button></h3><div id="acc-body-${i}" role="region" aria-labelledby="acc-${i}" ${i===0?'':'hidden'}><p>${x.body}</p></div></div>`).join('')}</div><div class="preview-stage" aria-label="Workflow preview">${c.accordion.map((x,i)=>`<article id="preview-${i}" class="preview-panel" ${i===0?'':'hidden'}>${meta('DEMONSTRATION / CONCEPTUAL WORKFLOW')}<p class="message">${x.prompt}</p><div class="preview-record">${meta('CONTINUUM / VERA-04')}<dl>${x.rows.map(([key,value])=>`<div><dt>${key}</dt><dd>${value}</dd></div>`).join('')}</dl></div><p class="preview-status">${x.status}</p></article>`).join('')}</div></div></section>
<section id="galaxy" class="galaxy"><div><p class="eyebrow">ONE PRINCIPAL / A WIDER FIELD</p><h2>${c.galaxy}</h2><p class="quiet">An architectural direction, explored through conceptual workflows.</p></div><div class="marquee" aria-label="Conceptual capabilities"><div class="marquee-track">${[0,1].map(i=>`<div ${i?'aria-hidden="true"':''}>${c.capabilities.map(x=>`<span>${x}</span>`).join('')}</div>`).join('')}</div></div></section>
<section id="trust" class="trust section-pad"><div class="section-intro">${meta('THE EFFECT BOUNDARY')}<h2>Accuracy by design.<br><em>Control by default.</em></h2><p>${c.trustBody}</p></div><article class="trust-row"><div><h3>${c.traceTitle}</h3><p>${c.traceBody}</p><a class="text-link" href="/#evidence">Inspect the bounded claim ↗</a></div>${clip('trace')}</article><article class="trust-row reverse">${clip('confirm')}<div><h3>${c.confirmTitle}</h3><p>${c.confirmBody}</p><p class="quiet">Demonstration only. Buttons change this example; they do not authorize or execute real work.</p></div></article><details class="evidence-scope"><summary>Current evidence boundary <span>CONT-PERSIST-001 / EFFECT-BOUNDARY-001</span></summary><p>${c.proof}</p><p>${c.exclusions}</p><a href="/#evidence">Read the claim summary ↗</a></details></section>
<section class="related section-pad" aria-label="Explore Asentxia">${c.related.map(x=>`<a class="related-item" href="${x.href}">${meta(x.meta)}<div class="related-visual ${x.type}" aria-hidden="true">${x.type==='evidence'?'<span>001 — PROPOSED</span><span>002 — REVIEWED</span><span>003 — RECORDED</span>':x.type==='interfaces'?'<span>ENVIRONMENT / STATE</span><span>AUTHORITY / EXECUTION</span><span>EVIDENCE / COORDINATION</span><span>COGNITION BOUNDARY</span>':'<span>VERA-04</span><span>Authority / Scoped</span><span>Operator / OPS</span>'}</div><h3>${x.title}<span>↗</span></h3><p>${x.body}</p></a>`).join('')}</section>
<footer id="closing"><div class="closing-copy">${meta('CONTINUUM /::/ COMMAND')}<h2>Persistent work.<br><em>Deliberate control.</em></h2><div class="actions">${button('Explore Continuum','/continuum/',true)}${button('Inspect evidence','/#evidence')}</div></div><div class="footer-bottom"><a class="brand" href="/">ASENTXIA SYSTEMS</a><span>© 2026</span><span>Architecture for autonomous intelligence.</span></div></footer></main></body></html>`}
