export const command = {
  eyebrow: 'Continuum /::/ Command',
  title: 'Command the continuum.',
  description: 'Natural language becomes prepared, authorized, evidenced work — inside Continuum, not beside it.',
  labels: ['Inspect state', 'Authorize effects', 'Issue capability'],
  lock: 'All of Continuum, on Command.',
  demoNote: 'Demonstration · Conceptual interface · Fictional data',
  walkthrough: [
    {title:'Hand off work to Command.',body:'A proposed effect begins with intent. The principal, scope, and requested evidence stay attached.',prompt:'Prepare an evidence capsule for principal VERA-04…',status:'Drafting effect',kind:'prepare'},
    {title:'Review and approve every action.',body:'Choose an authority envelope before the effect crosses its boundary.',prompt:'Which authority envelope should govern this effect?',status:'Awaiting operator review',kind:'authority'},
    {title:'No tabs, dashboards, or context switching.',body:'Follow the proposed effect through to its record, in one continuous conversation.',prompt:'Effect released',status:'Recorded in the demonstration ledger',kind:'release'},
  ],
  accordion: [
    {title:'Insight from durable state',body:'Inspect the principal and the state associated with its environment.',prompt:'Show the recovered state of VERA-04.',rows:[['Principal','VERA-04'],['Computer','CC-004'],['Recovery','Same-host process restart']],status:'Recovered state · illustrative record'},
    {title:'Classify work at scale',body:'Preview a proposed classification before applying it to a collection of work.',prompt:'Group these proposed effects by authority scope.',rows:[['Read state','3 proposed effects'],['Write capsule','2 proposed effects'],['External dispatch','Review required']],status:'Conceptual workflow · not an attested integration'},
    {title:'Invite operators / issue capabilities',body:'Make the operator, scope, and revocation boundary explicit.',prompt:'Prepare a scoped capability for operator OPS.',rows:[['Operator','OPS'],['Scope','capsule.prepare'],['Authority','Revocable']],status:'Capability proposal · not issued'},
    {title:'Release an effect',body:'Review the exact proposal at the Effect Boundary.',prompt:'Prepare this effect for release.',rows:[['Revision','REV-003'],['Capability','capsule.prepare'],['Decision','Awaiting authorization']],status:'No external action is performed'},
    {title:'Schedule continuity rules',body:'Explore how a continuity rule could be prepared and reviewed.',prompt:'Draft a continuity rule for this computer.',rows:[['Trigger','Process restart'],['Action','Inspect recovered state'],['Release','Operator review']],status:'Design concept · scheduling is not attested'},
  ],
  galaxy: 'The entire Continuum field is yours to command.',
  capabilities:['Inspect state','Prepare work','Review authority','Issue capability','Revoke a grant','Trace an effect','Recover state','Inspect evidence'],
  trustTitle:'Accuracy by design. Control by default.',
  trustBody:'The design connects proposed work to state, authority, and an inspectable record. These interfaces illustrate that architecture.',
  traceTitle:'A record you can follow.',
  traceBody:'From proposed effect to ordered record. The current documented slice includes structured evidence checked by an independent verifier.',
  confirmTitle:'Authority before effect.',
  confirmBody:'Cognition proposes. Authority constrains. Execution mediates. Evidence records. The confirmation below is an interactive demonstration.',
  proof:'Current documented scope: same-host process restart; persistent Continuum Computer ID and VERA ID; durable-state recovery; scoped authorization; revocation denial; mediated post-restart effect; ordered structured evidence; independent verifier. Exact public demo and P00–P01–P03 artifacts are pending.',
  exclusions:'This does not establish host migration, universal provider substitution, complete DCA conformance, production readiness, or cryptographic verification.',
  related:[
    {title:'Evidence',meta:'01 / THE RECORD',body:'Inspect the bounded claim and its present evidence boundary.',href:'/#evidence',type:'evidence'},
    {title:'Machine-native interfaces',meta:'02 / THE ARCHITECTURE',body:'Explore the seven responsibilities and the Effect Boundary.',href:'/architecture/',type:'interfaces'},
    {title:'Regency Console',meta:'03 / GOVERNANCE',body:'The authorized human administration and supervision client. Product direction; integration is not implied.',href:'/continuum/#regency',type:'regency'},
  ],
};
